# Php with Apache
FROM php:7.4-apache

# Install PHP extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Enable Apache mod_rewrite (needed for CodeIgniter routes)
RUN a2enmod rewrite

# Copy backend files into Apache webroot
COPY . /var/www/html/

# Set working dir
WORKDIR /var/www/html/

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Expose port
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]
